package BikeRunning;




import java.awt.Container;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 처음 초기 버전의 MainView는 직접 코드를 입력하여 만들었으나,
 * 최신 버전의 MainView에서는 
 * JFrame 객체를 이용하여 수정하기 쉬워졌음.
 * 부산시에서 지하철역을 가지고 있는 모든 구에 버튼을 추가함.
 * 
 * Final Version
 * @author SungYong, Sungrae, Dayoung
 */

public class MainView extends javax.swing.JFrame {
    ImageIcon icon; 
    DongMain dmain;
    JPanel background;
    Container contentPane; //Container클래스의 객체인 contentPane 생성. 
    
    
    public MainView() {
        initComponents(); 
        contentPane = getContentPane(); //ContentPane 객체를 얻음.
        contentPane.setLayout(null); //Layout을 null로 함.
        
        ImageIcon back;
        back=new ImageIcon("./img/busanMap.png"); //back이라는 ImageIcon의 객체에 배경화면을 저장.
        JLabel background= new JLabel(back); //부산시 지도를 JLabel클래스의 객체인 background로 선언.
        
        background.setLocation(0,0); //부산시 지도 좌표 설정.
        background.setSize(732, 475);//부산시 지도 크기 설정.
        contentPane.add(background); //contentPane 객체에 부산시 지도를 추가.
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //프레임 창을 종료할시 전체 프로그램이 멈추는 것을 막음.
        setSize(740, 500); //MainView 프레임의 크기
        setTitle("우리동네 한바퀴");
        setVisible(true); //화면 보이기
        setLocationRelativeTo(null); //프레임을 화면 정중앙으로 배치함.
        setResizable(false); //프레임 크기 조정 x
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jJingu = new javax.swing.JButton(new ImageIcon("./img/busan_Jingu.png"));
        jJingu.setOpaque(false);
        ;
        jBukgu = new javax.swing.JButton(new ImageIcon("./img/Busan_Bukgu.png"));
        jSasang = new javax.swing.JButton(new ImageIcon("./img/Sasang.png"));
        jGangseo = new javax.swing.JButton(new ImageIcon("./img/Gangseo.png"));
        jSaha = new javax.swing.JButton(new ImageIcon("./img/Saha.png"));
        jSeogu = new javax.swing.JButton(new ImageIcon("./img/Busan_Seogu.png"));
        jJunggo = new javax.swing.JButton(new ImageIcon("./img/Busan_Junggo.png"));
        jDonggu = new javax.swing.JButton(new ImageIcon("./img/Busan_Donggu.png"));
        jGeumjeong = new javax.swing.JButton(new ImageIcon("./img/Geumjeong.png"));
        jDongnae = new javax.swing.JButton(new ImageIcon("./img/Dongnae.png"));
        jYeonje = new javax.swing.JButton(new ImageIcon("./img/Yeonje.png"));
        jSuyeong = new javax.swing.JButton(new ImageIcon("./img/Suyeong.png"));
        jNamgu = new javax.swing.JButton(new ImageIcon("./img/Busan_Namgu.png"));
        jHaeundae = new javax.swing.JButton(new ImageIcon("./img/Haeundae.png"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jJingu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jJingu.setBorderPainted(false);
        jJingu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJinguActionPerformed(evt);
            }
        });

        jBukgu.setOpaque(false);
        jBukgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBukguActionPerformed(evt);
            }
        });

        jJingu.setOpaque(false);
        jSasang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSasangActionPerformed(evt);
            }
        });

        jGangseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGangseoActionPerformed(evt);
            }
        });

        jSaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSahaActionPerformed(evt);
            }
        });

        jSeogu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeoguActionPerformed(evt);
            }
        });

        jJunggo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJunggoActionPerformed(evt);
            }
        });

        jDonggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDongguActionPerformed(evt);
            }
        });

        jGeumjeong.setOpaque(false);
        jGeumjeong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGeumjeongActionPerformed(evt);
            }
        });

        jDongnae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDongnaeActionPerformed(evt);
            }
        });

        jYeonje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYeonjeActionPerformed(evt);
            }
        });

        jSuyeong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSuyeongActionPerformed(evt);
            }
        });

        jNamgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamguActionPerformed(evt);
            }
        });

        jHaeundae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHaeundaeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jDonggu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jGeumjeong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jYeonje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jHaeundae, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDongnae, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSasang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jGangseo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addComponent(jJingu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jBukgu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jSaha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeogu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJunggo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNamgu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSuyeong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jGeumjeong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jHaeundae, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBukgu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jDongnae, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jYeonje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSuyeong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jNamgu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jJingu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDonggu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addComponent(jJunggo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jSasang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jGangseo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jSeogu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jSaha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jJinguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJinguActionPerformed
          
        // TODO add your handling code here:
            if(evt.getSource() == jJingu){
            try {
                DongMain dongmain = new DongMain("부산진구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }      
    }//GEN-LAST:event_jJinguActionPerformed

    private void jBukguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBukguActionPerformed
        // TODO add your handling code here:
         if(evt.getSource() == jBukgu){
            try {
                DongMain dongmain = new DongMain("북구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }      
    }//GEN-LAST:event_jBukguActionPerformed

    private void jSahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSahaActionPerformed
        // TODO add your handling code here:
          if(evt.getSource() == jSaha){
            try {
                DongMain dongmain = new DongMain("사하구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }      
    }//GEN-LAST:event_jSahaActionPerformed

    private void jDongnaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDongnaeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jDongnae){
            try {
                DongMain dongmain = new DongMain("동래구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }    
    }//GEN-LAST:event_jDongnaeActionPerformed

    private void jHaeundaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHaeundaeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jHaeundae){
            try {
                DongMain dongmain = new DongMain("해운대구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jHaeundaeActionPerformed

    private void jSasangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSasangActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jSasang){
            try {
                DongMain dongmain = new DongMain("사상구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jSasangActionPerformed

    private void jNamguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamguActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jNamgu){
            try {
                DongMain dongmain = new DongMain("남구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jNamguActionPerformed

    private void jYeonjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYeonjeActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jYeonje){
            try {
                DongMain dongmain = new DongMain("연제구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jYeonjeActionPerformed

    private void jGangseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGangseoActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jGangseo){
            try {
                DongMain dongmain = new DongMain("강서구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jGangseoActionPerformed

    private void jSeoguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeoguActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jSeogu){
            try {
                DongMain dongmain = new DongMain("서구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jSeoguActionPerformed

    private void jJunggoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJunggoActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jJunggo){
            try {
                DongMain dongmain = new DongMain("중구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jJunggoActionPerformed

    private void jDongguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDongguActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jDonggu){
            try {
                DongMain dongmain = new DongMain("동구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jDongguActionPerformed

    private void jGeumjeongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGeumjeongActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jGeumjeong){
            try {
                DongMain dongmain = new DongMain("금정구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jGeumjeongActionPerformed

    private void jSuyeongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSuyeongActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == jSuyeong){
            try {
                DongMain dongmain = new DongMain("수영구");
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_jSuyeongActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBukgu;
    private javax.swing.JButton jDonggu;
    private javax.swing.JButton jDongnae;
    private javax.swing.JButton jGangseo;
    private javax.swing.JButton jGeumjeong;
    private javax.swing.JButton jHaeundae;
    private javax.swing.JButton jJingu;
    private javax.swing.JButton jJunggo;
    private javax.swing.JButton jNamgu;
    private javax.swing.JButton jSaha;
    private javax.swing.JButton jSasang;
    private javax.swing.JButton jSeogu;
    private javax.swing.JButton jSuyeong;
    private javax.swing.JButton jYeonje;
    // End of variables declaration//GEN-END:variables
}
